version: "3.8"

services:
  node-app:
    build: .
    container_name: portfolio-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - portfolio-network
    restart: always
    volumes:
      - ./:/usr/src/app

  db:
    image: mysql:8.0
    container_name: portfolio-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: portfolio_user
      MYSQL_PASSWORD: securepassword
    ports:
      - "3306:3306"
    networks:
      - portfolio-network
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always

volumes:
  db_data:

networks:
  portfolio-network:
    external: true
