version: '3.8'
services:
  jenkins:
    build: ./jenkins       # builds from your jenkins/Dockerfile
    container_name: portfolio-jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   # still map host docker sock
      - jenkins_home:/var/jenkins_home
    restart: always

volumes:
  jenkins_home:
