version: '3.8'

services:
  # --------------------------------
  # 1. Jenkins CI/CD Server Container
  # --------------------------------
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    privileged: true # Required for Docker client access
    ports:
      - "5000:8080" # Jenkins web UI
      - "50000:50000" # Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home # Persistent Jenkins data
      # Mount host's Docker socket and binary for pipeline to execute docker commands
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the Docker Compose binary from the host (assuming it's installed there)
      # NOTE: This path might vary. Common Linux path is /usr/local/bin/docker-compose or /usr/bin/docker-compose
      - /usr/bin/docker-compose:/usr/bin/docker-compose
    environment:
      TZ: Asia/Kolkata # Optional: set timezone
    restart: always

  # --------------------------------
  # 2. Application Container
  # --------------------------------
  app:
    image: syed048/portfolio-app:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

  # --------------------------------
  # 3. MySQL Database Container
  # --------------------------------
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123admin
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: syed
      MYSQL_PASSWORD: 123admin
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always
    ports:
      - "3306:3306"

  # --------------------------------
  # 4. Adminer (DB UI) Container
  # --------------------------------
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  jenkins_home:
  db_data:
