version: '3.8'
services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    image: jenkins-with-docker:latest
    container_name: jenkins
    ports:
      - "8080:8080"   # Jenkins Web UI
      - "50000:50000" # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # allow Jenkins to use host docker daemon
      - /usr/bin/docker:/usr/bin/docker   # optional: host docker binary (if available)
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home:
