version: '3.8'

services:
  # --------------------------------
  # 1. Jenkins CI/CD Server Container
  # --------------------------------
  jenkins:
    # Using the official LTS image
    image: jenkins/jenkins:lts
    user: root # Necessary for full access to mounted Docker tools
    privileged: true 
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      # CRITICAL: Mount the Docker socket and host binaries for Docker-out-of-Docker (DooD)
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/bin/docker-compose:/usr/bin/docker-compose
    environment:
      TZ: Asia/Kolkata
    restart: always
    networks:
      - portfolio_network

  # --------------------------------
  # 2. Application Container (Node)
  # --------------------------------
  app:
    image: syed048/portfolio-app:latest
    env_file:
      - .env
    ports:
      - "80:3000"
    depends_on:
      - db
    restart: always
    networks:
      - portfolio_network

  # --------------------------------
  # 3. MySQL Database Container
  # --------------------------------
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123admin
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: syed
      MYSQL_PASSWORD: 123admin
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always
    networks:
      - portfolio_network

  # --------------------------------
  # 4. Adminer (DB UI) Container
  # --------------------------------
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge

volumes:
  jenkins_home:
  db_data:
