version: "3.8"

services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: portfolio-jenkins
    ports:
      - "5000:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portfolio-network
    environment:
      - DOCKER_HUB_CREDENTIALS=dockerhub-creds
      - GITHUB_CREDENTIALS=github-creds
    restart: always

volumes:
  jenkins_home:

networks:
  portfolio-network:
    external: true
