version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    user: root
    ports:
      - "5000:8080"  # Jenkins UI
      - "50000:50000" # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      `- /var/run/docker.sock:/var/run/docker.sock
    restart: always

  app:
    image: syed048/portfolio-app:latest
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: syed
      MYSQL_PASSWORD: 123admin
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always
    ports:
      - "3306:3306"

volumes:
  db_data:
  jenkins_home:

