version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: portfolio-db
    environment:
      MYSQL_ROOT_PASSWORD: 123admin
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: syed
      MYSQL_PASSWORD: 123admin
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p123admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s

  app:
    build: .
    image: syed048/portfolio-app:latest
    container_name: portfolio-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: ["sh", "-c", "until nc -z db 3306; do echo 'Waiting for DB...'; sleep 5; done; node server.js"]

  adminer:
    image: adminer
    container_name: portfolio-adminer
    ports:
      - "8081:8080"
    restart: always

volumes:
  db_data:

