version: '3.9'

services:
  app:
    build: .
    container_name: portfolio-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
    restart: always

  db:
    image: mysql:8.0
    container_name: portfolio-db
    environment:
      MYSQL_ROOT_PASSWORD: 123admin
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: syed
      MYSQL_PASSWORD: 123admin
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    restart: always

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "5000:8080"   # Jenkins UI
      - "5001:50000"  # JNLP agent port
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always
    environment:
      # Do NOT disable setup wizard here, remove JAVA_OPTS
      # JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

volumes:
  db_data:
  jenkins_home:

