services:
  db:
    image: mysql:8.0
    container_name: portfolio-db
    environment:
      MYSQL_ROOT_PASSWORD: 123admin
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: syed
      MYSQL_PASSWORD: 123admin
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u syed -p123admin"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 20s

  app:
    image: syed048/portfolio-app:latest
    container_name: portfolio-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  adminer:
    image: adminer
    container_name: portfolio-adminer
    ports:
      - "8081:8080"
    restart: always

volumes:
  db_data:

