version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    privileged: true # Required for mounting the Docker socket and running DinD commands
    user: root # Run as root to avoid permission issues with the mounted socket
    ports:
      - "5000:8080"
      - "50000:50000"
    volumes:
      # Mount the Docker CLI and socket for DooD (Jenkins uses host Docker daemon)
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      # Persist Jenkins data
      - jenkins_home:/var/jenkins_home
      # Mount your project's directory into the Jenkins container for the pipeline to access your docker-compose.yml and .env
      - .:/home/jenkins/project:rw
    environment:
      # This is the path inside the container where the project code is mapped
      - PROJECT_PATH=/home/jenkins/project
    restart: always

volumes:
  jenkins_home:
