version: "3.8"
services:
  node-app:
    build: .
    container_name: portfolio-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
    volumes:
      - ./:/usr/src/app

  db:
    image: mysql:8.0
    container_name: portfolio-db
    environment:
      MYSQL_ROOT_PASSWORD: 123admin
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: syed
      MYSQL_PASSWORD: 123admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: portfolio-jenkins
    user: root
    ports:
      - "5000:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HUB_CREDENTIALS=dockerhub-creds
      - GITHUB_CREDENTIALS=github-creds
    restart: always

volumes:
  db_data:
  jenkins_home:
