version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   # allows Jenkins to run docker
      - jenkins_home:/var/jenkins_home
    restart: always

volumes:
  jenkins_home:

