version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    # Use privileged mode, which is often necessary for proper Docker socket access
    privileged: true 
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # CRITICAL: Mount the host's Docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      # CRITICAL: Persist Jenkins data
      - jenkins_home:/var/jenkins_home
      # Mount the Docker binary from the host
      - /usr/bin/docker:/usr/bin/docker
      # Mount docker-compose binary from the host
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    environment:
      - TZ=Asia/Kolkata
    restart: always

volumes:
  jenkins_home:
