version: '3.8'

services:
  # --------------------------------
  # 1. Jenkins CI/CD Server Container
  # --------------------------------
  jenkins:
    # Use build instead of image
    build: 
      context: .
      dockerfile: Dockerfile.jenkins
    # We still need the 'privileged' flag and 'user: root' if 'usermod' fails, 
    # but 'user: jenkins' is safer if permissions work. Using 'user: root' for simplicity.
    user: root 
    privileged: true 
    ports:
      - "5000:8080" # Jenkins web UI
      - "50000:50000" # Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home # Persistent Jenkins data
      # CRITICAL: Mount ONLY the Docker socket. The client and compose binaries are now internal.
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Asia/Kolkata
    restart: always

  # --------------------------------
  # 2. Application Container
  # --------------------------------
  app:
    image: syed048/portfolio-app:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

  # --------------------------------
  # 3. MySQL Database Container
  # --------------------------------
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123admin
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: syed
      MYSQL_PASSWORD: 123admin
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always
    ports:
      - "3306:3306"

  # --------------------------------
  # 4. Adminer (DB UI) Container
  # --------------------------------
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  jenkins_home:
  db_data:
